GET http://localhost:8000/api/ELB1905STR/info

###
GET http://localhost:8000/api/LUTH1912/info

###
GET http://localhost:8000/api/ELB1905STR/47/1

###
GET http://localhost:8000/api/LUTH1912/47/1

###
GET http://localhost:8000/api/ELB1905STR/Abraham

###
GET http://localhost:8000/api/translations.json

###
GET http://localhost:8000/api/LUTH1912/47/1.json

###
GET http://localhost:8000/api/ELB1905STR/47/1/3.json

###
GET http://localhost:8000/api/ELB1905STR/greek_strongs/1001.json

### Search
GET http://localhost:8000/api/ELB1905STR/"jesus%20kam"%20thomas

### Search
GET http://localhost:8000/api/ELB1905STR/jesus%20thomas